apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  labels:
    app: go-app-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app-server
  template:
    metadata:
      labels:
        app: go-app-server
    spec:
      containers:
      - name: go-app-server
        image: goapp:version2
        ports:
        - containerPort: 4444
        envFrom:
        - configMapRef:
            name: goapp-config
        volumeMounts:
        - name: redis-storage
          mountPath: "/var/lib/redis"
        - name: secret-volume
          mountPath: "/app/secrets"
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: goapp-secrets
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
